from typing import Optional, Sequence, Union

from .gate import QuantumGate

GateSequence = Union[ImmutableQuantumCircuit, Sequence[QuantumGate]]

class ImmutableQuantumCircuit:
    def __init__(self, circuit: "ImmutableQuantumCircuit") -> None: ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def qubit_count(self) -> int: ...
    @property
    def cbit_count(self) -> int: ...
    @property
    def gates(self) -> Sequence[QuantumGate]: ...
    @property
    def depth(self) -> int: ...
    def combine(self, gates: GateSequence) -> "QuantumCircuit": ...
    def __add__(self, gates: GateSequence) -> "QuantumCircuit": ...
    def freeze(self) -> "ImmutableQuantumCircuit": ...
    def get_mutable_copy(self) -> "QuantumCircuit": ...

class QuantumCircuit(ImmutableQuantumCircuit):
    def __init__(
        self, qubit_count: int, cbit_count: int = 0, gates: Sequence[QuantumGate] = []
    ) -> None: ...
    def add_gate(self, gate: QuantumGate, gate_index: Optional[int] = None) -> None: ...
    def extend(self, gates: GateSequence) -> None: ...
    def __iadd__(self, gates: GateSequence) -> "QuantumCircuit": ...
    def add_X_gate(self, qubit_index: int) -> None: ...
    def add_Y_gate(self, qubit_index: int) -> None: ...
    def add_Z_gate(self, qubit_index: int) -> None: ...
    def add_H_gate(self, qubit_index: int) -> None: ...
    def add_S_gate(self, qubit_index: int) -> None: ...
    def add_Sdag_gate(self, qubit_index: int) -> None: ...
    def add_SqrtX_gate(self, qubit_index: int) -> None: ...
    def add_SqrtXdag_gate(self, qubit_index: int) -> None: ...
    def add_SqrtY_gate(self, qubit_index: int) -> None: ...
    def add_SqrtYdag_gate(self, qubit_index: int) -> None: ...
    def add_T_gate(self, qubit_index: int) -> None: ...
    def add_Tdag_gate(self, qubit_index: int) -> None: ...
    def add_U1_gate(self, qubit_index: int, lmd: float) -> None: ...
    def add_U2_gate(self, qubit_index: int, phi: float, lmd: float) -> None: ...
    def add_U3_gate(
        self, qubit_index: int, theta: float, phi: float, lmd: float
    ) -> None: ...
    def add_RX_gate(self, qubit_index: int, angle: float) -> None: ...
    def add_RY_gate(self, qubit_index: int, angle: float) -> None: ...
    def add_RZ_gate(self, qubit_index: int, angle: float) -> None: ...
    def add_CNOT_gate(self, control_index: int, target_index: int) -> None: ...
    def add_CZ_gate(self, control_index: int, target_index: int) -> None: ...
    def add_SWAP_gate(self, target_index1: int, target_index2: int) -> None: ...
    def add_TOFFOLI_gate(
        self, control_index1: int, control_index2: int, target_index: int
    ) -> None: ...
