from typing import Optional, Sequence, Tuple, Union

from .circuit import GateSequence, QuantumCircuit
from .gate import ParametricQuantumGate, QuantumGate
from .parameter import Parameter

class ImmutableParametricQuantumCircuit:
    def __init__(self, circuit: "ImmutableParametricQuantumCircuit") -> None: ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def qubit_count(self) -> int: ...
    @property
    def cbit_count(self) -> int: ...
    @property
    def gates(self) -> Sequence[QuantumGate]: ...
    @property
    def gates_and_params(
        self,
    ) -> Sequence[
        Union[Tuple[QuantumGate, None], Tuple[ParametricQuantumGate, Parameter]]
    ]: ...
    @property
    def has_trivial_parameter_mapping(self) -> bool: ...
    @property
    def depth(self) -> int: ...
    def combine(
        self, gates: Union[GateSequence, "ImmutableParametricQuantumCircuit"]
    ) -> "ParametricQuantumCircuit": ...
    def __add__(
        self, gates: Union[GateSequence, "ImmutableParametricQuantumCircuit"]
    ) -> "ParametricQuantumCircuit": ...
    def freeze(self) -> "ImmutableParametricQuantumCircuit": ...
    def get_mutable_copy(self) -> "ParametricQuantumCircuit": ...

class ParametricQuantumCircuit(ImmutableParametricQuantumCircuit):
    def __init__(self, qubit_count: int, cbit_count: int = 0) -> None: ...
    def add_gate(self, gate: QuantumGate, gate_index: Optional[int] = None) -> None: ...
    def extend(
        self, gates: Union[GateSequence, "ImmutableParametricQuantumCircuit"]
    ) -> None: ...
    def __iadd__(
        self, gates: Union[GateSequence, "ImmutableParametricQuantumCircuit"]
    ) -> "ParametricQuantumCircuit": ...
    def add_ParametricRX_gate(self, qubit_index: int) -> None: ...
