[package]
name = "quri-parts-qulacs"
version = "0.19.0"
edition = "2021"
publish = false

[dependencies]
num-complex = "0.4.6"
quri-parts = { path = "../../", version = "0.19.0", features = ["python"] }
abi_stable = "=0.11.3"
quri-parts-circuit = { path = "../circuit/", version = "0.19.0" }
pyo3-commonize = "0.1.2"

[dependencies.pyo3]
version = "*"
features = ["extension-module", "macros", "num-complex", "py-clone"]

[lib]
path = "rust/lib.rs"
crate-type = ["rlib", "cdylib"]
