[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quri-parts-openqasm"
version = "0.0.0"
description = "A support library for using OpenQASM 3 with QURI Parts"
authors = ["QURI Parts Authors <opensource@qunasys.com>"]
readme = "README.md"
repository = "https://github.com/QunaSys/quri-parts"
documentation = "https://quri-parts.qunasys.com"
keywords = ["quantum", "quantum computing"]
classifiers = [
    "Topic :: Scientific/Engineering :: Physics",
    "Typing :: Typed"
]
packages = [
    { include = "quri_parts" }
]

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[tool.poetry.dependencies]
python = ">=3.9.8,<3.12"
quri-parts-circuit = "*"

[tool.poetry.group.dev.dependencies]
quri-parts-circuit = {path = "../circuit", develop = true}

pytest = "^7.0.1"
flake8 = "^4.0.1"
mypy = ">=0.950"
docformatter = "^1.4"
isort = "^5.10.1"
black = "^23.1.0"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
