name: Setup

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ github.token }}

    - name: git config
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf https://github.com/
    
    - name: Install jq
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.6'
        force: true

    - name: Install Poetry
      shell: bash
      env:
        POETRY_VERSION: 1.8.0
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
