name: Lint

on:
  pull_request:
    paths:
      - '**.py'
      - pyproject.toml
      - poetry.lock
      - .flake8
      - .github/workflows/lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup
      with:
        poetry-version: '1.8.0'
        python-version: '3.10'

    - run: |
        poetry env use 3.10
        poetry install

    - run: poetry run isort . --check --diff
      if: success() || failure()

    - run: poetry run black . --check
      if: success() || failure()

    - run: poetry run flake8 .
      if: success() || failure()

    - run: poetry run mypy .
      if: success() || failure()
