name: Check notebook diff

on:
  pull_request:

jobs:
  check-clean:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/setup

    - run: |
        make -s clean-nb
        
    - run: |
        git diff --exit-code
