name: Contributor License Agreement

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest

    steps:
    - name: Get CLA Manager access token
      id: cla-token
      uses: getsentry/action-github-app-token@v2.0.0
      with:
        app_id: ${{ secrets.CLA_MANAGER_APP_ID }}
        private_key: ${{ secrets.CLA_MANAGER_PRIVATE_KEY}}

    - name: cla
      if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
      uses: contributor-assistant/github-action@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ steps.cla-token.outputs.token }}
      with:
        path-to-document: 'https://cla.qunasys.com'
        remote-organization-name: 'QunaSys'
        remote-repository-name: 'cla'
        branch: 'main'
        path-to-signatures: 'signatures/v1/cla.json'
        custom-notsigned-prcomment: '<br/>Thank you for your submission, we really appreciate it. We ask that $you sign our [Contributor License Agreement](https://cla.qunasys.com) before we can accept your contribution. This CLA will also cover your future contributions submitted to QunaSys. You can sign the CLA by just posting a pull request comment same as the below format.<br/>'
        allowlist: dependabot*