name: Check all notebooks

on:
  pull_request:
    paths:
      - notebooks/poetry.lock
      - notebooks/pyproject.toml

defaults:
  run:
    working-directory: notebooks

jobs:
  execute-all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/notebooks/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry install

    - run: |
        for f in $(find quri_sdk_notebooks -mindepth 1 -type f -name *.ipynb)
        do
          if grep -Fxq $f .exclude
          then
            echo "Skipping execution of $f"
          else
            echo "Executing $f"
            start=$(date +%s)
            poetry run jupyter execute --inplace --JupyterApp.log_level=50 $f
            end=$(date +%s)
            seconds=$((end-start))
            echo "Elapsed: $(($seconds / 3600))hrs $((($seconds / 60) % 60))min $(($seconds % 60))sec"
          fi
        done
    