name: Check modified notebooks

on:
  pull_request:
    paths:
      - 'notebooks/quri_sdk_notebooks/**.ipynb'

defaults:
  run:
    working-directory: notebooks
    

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/notebooks/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        git fetch

    - run: |
        poetry install

    - run: |
        for f in $(git diff --name-only origin/main quri_sdk_notebooks/ | grep .ipynb)
        do
          if grep -Fxq $f .exclude
          then
            echo "Skipping execution of $f"
          else
            echo "Executing $f"
            poetry run jupyter execute --inplace --JupyterApp.log_level=50 $f
          fi
        done
        