name: Pull upstream changes

on:
  schedule:
    - cron: '0 0 * * MON-FRI'
  workflow_dispatch:

jobs:
  pull-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - run: git pull --ff-only https://github.com/QunaSys/quri-parts.git
    - run: git push
