name: Lint

on:
  pull_request:
    paths:
      - 'quri-vm/**.py'
      - quri-vm/pyproject.toml
      - quri-vm/poetry.lock
      - quri-vm/.flake8
      - .github/workflows/quri-vm-lint.yml
  push:
    branches: [main]

defaults:
  run:
    working-directory: quri-vm

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-vm/setup
      with:
        poetry-version: '1.8.0'
        python-version: '3.10'

    - run: |
        poetry env use 3.10
        poetry install

    - run: poetry run isort . --check --diff
      if: success() || failure()

    - run: poetry run black . --check
      if: success() || failure()

    - run: poetry run flake8 .
      if: success() || failure()

    - run: poetry run mypy .
      if: success() || failure()
