name: QURI Algo Test

on:
  pull_request:
    paths:
      - quri-algo/pyproject.toml
      - quri-algo/poetry.lock
      - quri-algo/quri_algo/**.py
      - .github/workflows/quri-algo-pytest.yml
  push:
    branches: [main]

defaults:
  run:
    working-directory: quri-algo

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-algo/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry env use python3.11
        poetry install

    - run: poetry run pytest tests/