name: QURI Parts Test

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/packages/**/*.rs
      - quri-parts/./**/Cargo.toml
      - quri-parts/./**/Cargo.lock
      - quri-parts/rust/**/*.rs
      - quri-parts/poetry.lock
      - .github/workflows/quri-parts-test.yml
      - .github/actions/quri-parts/python-poetry-install/action.yml
      - .github/actions/quri-parts/rust-install-cache/action.yml
      - quri-parts/**/*.jl
  push:
    branches: [main]

defaults:
  run:
    working-directory: quri-parts

jobs:
  test:

    strategy:
      matrix:
        python_version:
          - '3.9'
          - '3.10'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-parts/python-poetry-install
      with:
        poetry-version: '1.4.0'
        python-version: ${{ matrix.python_version }}

    - uses: ./.github/actions/quri-parts/rust-install-cache
      with:
        toolchain: "stable"
        additional-key: "test"

    - uses: actions/cache@v3
      with:
        path: |
          ~/.julia/
        key: ci-${{ runner.os }}-julia-${{ hashFiles('poetry.lock') }}-cache
        restore-keys: ci-${{ runner.os }}-julia-

    - working-directory: quri-parts
      run: |
        cargo test --workspace --manifest-path quri-parts/Cargo.toml

    - run: |
        poetry env use ${{ matrix.python_version }}
        poetry run pip install -vvv -e quri-parts/packages/rust
        poetry install -vvv --only main,dev

    - run: |
        poetry run python -c "import juliapkg; print('PROJECT={}'.format(juliapkg.project()))" | sed -ne '/^PROJECT=/p' >> "$GITHUB_OUTPUT"
      id: julia_project

    - run: |
        poetry run julia  "--project=${{ steps.julia_project.outputs.PROJECT }}" -e 'using Pkg; Pkg.add("PythonCall"); Pkg.instantiate()'

    - run: |
        poetry run pytest quri-parts
