name: Lint

on:
  pull_request:
    paths:
      - quri-parts/packages/**/*.py
      - quri-parts/packages/**/*.rs
      - quri-parts/rust/**/*.rs
      - quri-parts/pyproject.toml
      - quri-parts/poetry.lock
      - quri-parts/.flake8
      - .github/workflows/quri-parts-lint.yml
      - .github/actions/quri-parts/python-poetry-install/action.yml
      - .github/actions/quri-parts/rust-install-cache/action.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/quri-parts/python-poetry-install
      with:
        poetry-version: '1.4.0'
        python-version: '3.10'

    - uses: ./.github/actions/quri-parts/rust-install-cache
      with:
        toolchain: "nightly"
        additional-key: "lint"

    - name: Install fmt
      run: rustup component add rustfmt

    - name: Run format
      run: cargo fmt --all -- --check
      if: success() || failure()

    - run: |
        cd quri-parts
        poetry env use 3.10
        poetry install --only lint

    - run: |
        cd quri-parts
        poetry run isort packages --check --diff
      if: success() || failure()

    - run: |
        cd quri-parts
        poetry run black packages --check
      if: success() || failure()

    - run: |
        cd quri-parts
        poetry run flake8 packages
      if: success() || failure()

    - run: |
        cd quri-parts
        poetry run docformatter -c -r packages
      if: success() || failure()
